### ISSUE TITLE
Reduce noise in sparse matmul benchmarks

### ISSUE THREAD

**Issue by ararslan** [JuliaCI/BaseBenchmarks.jl#135]
Lately on Julia master, the sparse matmul benchmarks have been showing a lot of spurious improvements and regressions. It would be great if we could determine why they're so noisy and adjust them as needed.

@Sacha0, would you be willing to take a crack at this?

**Comment by andreasnoack** [comment]
I guess we'll need to fix the sparsity patterns for the sparse test matrices.

**Comment by Sacha0** [comment]
Did `@KristofferC`'s recent pull request do the trick? Or does this issue require further attention? Best!

**Comment by ararslan** [comment]
That remains to be seen; we'll have to do more Nanosoldier runs on Base to see what happens.

**Comment by ararslan** [comment]
The sparse matmul benchmarks have been looking better lately, I think. What do you folks think?

**Comment by Sacha0** [comment]
> The sparse matmul benchmarks have been looking better lately, I think. What do you folks think?

Seems that `@KristofferC`'s patch did the trick? :)

**Comment by ararslan** [comment]
Yeah seems so. Thanks Kristoffer!
