### ISSUE TITLE
Fix deprecations for 0.7

### ISSUE THREAD

**Issue by ararslan** [JuliaCI/BaseBenchmarks.jl#158]
This issue will be a holding ground for various deprecations in 0.7 that are not yet fixed here.

- [x] `A_mul_B` and friends
- [x] `.'` transpose
- [x] `Void`
- [x] `replace` without `Pair`s
- [x] `search`, `searchindex`
- [x] Implicit assignment to global variables
- [x] Parametric method syntax generated from hdindexing
- [x] `Array` constructor without `uninitialized`
- [x] `sub2ind`
- [x] `CartesianRange`
- [x] `parse(::String)`
- [x] `Vector{UInt8}(::String)`
- [x] `find`
- [x] `parse` in a base without a kwarg
- [x] `method_exists`
- [x] `indmin`/`indmax`

**Comment by ararslan** [comment]
@Sacha0 Would you have time to help with the `A_mul_B` stuff here? Is that possible to do in a way that works in both 0.6 and 0.7?

**Comment by Sacha0** [comment]
(Will have a look at `.'` post #162 :).)

**Comment by ararslan** [comment]
@nalimilan Would you be willing to help out with the `search` and `find` stuff here?

**Comment by nalimilan** [comment]
https://github.com/JuliaLang/Compat.jl/pull/484 should help.

**Comment by ararslan** [comment]
Everything on this list has now been checked off!
