### ISSUE TITLE
0.7 deprecations, take 2

### ISSUE THREAD

**Issue by ararslan** [JuliaCI/BaseBenchmarks.jl#189]
Part 2 in the rousing series that began with #158. Things that are deprecated in 0.7 that we need to fix here:

- [x] `linspace`
- [x] `repmat`

**Comment by ararslan** [comment]
Typically we just wrap them in version checks with the new signatures, unless they're actually benchmarking different things.

**Comment by KristofferC** [comment]
Yeah, but there doesn't seem to be a straight up rename.

**Comment by Sacha0** [comment]
Happy to have a look at decomposition invocations if you would appreciate another pair of eyes on them; just point me where relevant :). Best!
