### ISSUE TITLE
Problem suite takes >40 minutes to load

### ISSUE THREAD

**Issue by ararslan** [JuliaCI/BaseBenchmarks.jl#202]
I tried it on a beefy remote machine and it was taking so long to load that I had to kill it after 40 minutes. This is also what's causing the 0.7 Travis builds to get killed, as it sits for 10 minutes with no output, which is Travis' limit.

**Comment by ararslan** [comment]
The log for a recent Nanosoldier build shows 1832 seconds (~30.5 minutes) to load the problem suite.

**Comment by KristofferC** [comment]
Fixed in https://github.com/JuliaCI/BaseBenchmarks.jl/pull/212
