### ISSUE TITLE
Sparse matvec tests broken on 0.6

### ISSUE THREAD

**Issue by andreasnoack** [JuliaCI/BaseBenchmarks.jl#243]
See https://travis-ci.org/JuliaCI/BaseBenchmarks.jl/jobs/464284112

**Comment by ararslan** [comment]
We should just drop 0.6 here. (See #246)

**Comment by KristofferC** [comment]
There where many regressions from 0.6 to 0.7. In some sense, it would be nice to be able to see how those are doing vs master, even if there is no new 0.6 release planned.

**Comment by ararslan** [comment]
Okay, that's fair.

**Comment by NHDaly** [comment]
The `v0.6` tests are still broken on travis in this repo.

Since no one has fixed them for 6 months, it seems that no one is using it.

We discussed this on Slack just now, and another point that came up is:
> Nanosoldier is the only user of BaseBenchmarks AFAIK, but that's mostly used to track regressions for PRs on master and for comparing branches for new releases

I also think it makes sense to drop support for `0.6`.
