### ISSUE TITLE
Drop 0.6

### ISSUE THREAD

**Issue by ararslan** [JuliaCI/BaseBenchmarks.jl#246]
It's pretty clear that there will be no more 0.6 releases. The potential for another 0.6 release was the only reason we still run 0.6 on CI and make heavy use of Compat here. I think it's now safe to drop 0.6 support.

Tasks:
- [ ] Remove version conditionals
- [ ] Remove Compat dependency
- [ ] Simplify any code that worked around 0.6 differences
- [ ] Remove 0.6 from CI

**Comment by ararslan** [comment]
@KristofferC's objection in https://github.com/JuliaCI/BaseBenchmarks.jl/issues/243#issuecomment-449719435:

> There where many regressions from 0.6 to 0.7. In some sense, it would be nice to be able to see how those are doing vs master, even if there is no new 0.6 release planned.

That seems like a good reason to keep it for now, so let's hold off on this.

**Comment by KristofferC** [comment]
Fine, let's do this :P
