### ISSUE TITLE
New tuning + update with latest benchmarks

### ISSUE THREAD

**Issue by KristofferC** [JuliaCI/BaseBenchmarks.jl#261]
@ararslan would be good if Nanosoldier could get refreshed with the latest benchmarks and possibly a retune.

**Comment by nalimilan** [comment]
Bump.

**Comment by vtjnash** [comment]
IIUC, tuning happens via GitHub actions now (and was done recently)

**Comment by christopher-dG** [comment]
Yeah, it is not happening currently because of the recent downtime, but when that's solved it will resume happening automatically.
