### ISSUE TITLE
libhdf5 error

### ISSUE THREAD

**Issue by timholy** [JuliaCI/BaseBenchmarks.jl#83]
FYI I'm seeing a strange error that starts with libhdf5 messages of which the relevant portion seems to be
```
...
  #010: ../../../src/H5FDint.c line 207 in H5FD_read(): addr overflow, addr = 140424345352640, size=512, eoa=1905739
    major: Invalid arguments to routine
    minor: Address overflowed
ERROR: LoadError: Error dereferencing object
Stacktrace:
...
```
It turns out this can be circumvented by replacing
```julia
BaseBenchmarks.loadall!()
```
with
```julia
BaseBenchmarks.load!("linalg")
BaseBenchmarks.loadall!()
```

Filing this without understanding what is actually going wrong, in case someone else encounters this.

**Comment by ararslan** [comment]
No longer relevant, as neither BaseBenchmarks nor BenchmarkTools depends on JLD.
